# version: '3.7'
#
# services:
#   db:
#     image: postgres:10.1-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#   web:
#     build: .
#     command: python /code/manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/databox
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#
# volumes:
#   postgres_data:

version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    image: databox
    command: python /databox/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/databox
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - migration
  migration:
    build: .
    image: databox
    command: python /databox/manage.py migrate --noinput
    volumes:
      - .:/databox
    links:
      - db
    depends_on:
      - db

volumes:
  postgres_data:
