# Generated by Django 2.2.1 on 2019-05-16 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20190515_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleoauth2token',
            name='profile_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='googleoauth2token',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='googleoauth2token',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='googleoauth2token',
            name='expires',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='googleoauth2token',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='googleoauth2token',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='googleoauth2token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
