# Generated by Django 2.2.1 on 2019-05-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20190519_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githuboauth2token',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='githuboauth2token',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
